services:
  frontend:
    build:
      context: ./apartments-catalog-app
      dockerfile: ./dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./apartments-catalog-app/:/usr/src/app
    depends_on:
      - backend
    environment:
      API_URL: http://backend:3001

  backend:
    build:
      context: ./apartments-catalog-service
      dockerfile: ./dockerfile
      target: development
    command: npm run start:dev
    ports:
      - 3001:3001
    volumes:
      - ./apartments-catalog-service/:/usr/src/app
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo
    ports:
      - 27017:27017

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
      MINIO_SERVER_URL: http://localhost:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
